set_property SRC_FILE_INFO {cfile:/home/seshan/fpga_test_reference/connectal/constraints/xilinx/vcu108.xdc rfile:../../../connectal/constraints/xilinx/vcu108.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AL9  [get_ports { CLK_pci_sys_clk_p }]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AL8  [get_ports { CLK_pci_sys_clk_n }]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AM17 [get_ports { RST_N_pci_sys_reset_n }]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G31  [get_ports { CLK_sys_clk1_300_p }]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F31  [get_ports { CLK_sys_clk1_300_n }]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G22  [get_ports { CLK_sys_clk2_300_p }]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G21  [get_ports { CLK_sys_clk2_300_n }]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports { CLK_sys_clk1_300_p }]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports { CLK_sys_clk1_300_n }]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports { CLK_sys_clk2_300_p }]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL12 [get_ports { CLK_sys_clk2_300_n }]
