
set partname {xcvu095-ffva2104-2-e}
set boardname {vcu108}
## for compatibility with older fpgamake. will be removed.
set xbsvipdir {/home/seshan/fpga_test_reference/connectal/out}
set ipdir {/home/seshan/fpga_test_reference/connectal/out}
set connectaldir {/home/seshan/fpga_test_reference/connectal}
set need_pcie {xu_gen3x8}
set connectal_dut {mkPcieTop}
set TRACE_PORTAL {}
set ConnectalVersion {22.05.23b}
set NumberOfMasters {1}
set PinType {Empty}
set PinTypeInclude {Misc}
set NumberOfUserTiles {1}
set SlaveDataBusWidth {32}
set SlaveControlAddrWidth {5}
set BurstLenSize {10}
set project_dir {$(DTOP)}
set MainClockPeriod {4}
set DerivedClockPeriod {4.000000}
set PcieClockPeriod {4}
set XILINX {1}
set VirtexUltrascale {}
set XilinxUltrascale {}
set PCIE {}
set PCIE3 {}
set PcieHostInterface {}
set PhysAddrWidth {40}
set NUMBER_OF_LEDS {2}
set PcieLanes {8}
set CONNECTAL_BITS_DEPENDENCES {hw/mkTop.bit}
set CONNECTAL_RUN_SCRIPT {$(CONNECTALDIR)/scripts/run.pcietest}
set BOARD_vcu108 {}
