//
// Generated by Bluespec Compiler (build 7d25cde)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_deq,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_indications_2_first,
// 					  portalIfc_indications_2_deq,
// 					  portalIfc_indications_2_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  ifc_say,
// 					  ifc_say2,
// 					  ifc_setLeds );
//
// schedule portalIfc_indications_0_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_say,
// 					     ifc_say2,
// 					     ifc_setLeds );
// schedule portalIfc_indications_0_first  SB ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty,
// 					   ifc_say,
// 					   ifc_say2,
// 					   ifc_setLeds );
// schedule portalIfc_indications_0_deq  C ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_say2,
// 						ifc_setLeds );
// schedule portalIfc_indications_0_notEmpty  SB ( portalIfc_indications_0_deq,
// 						ifc_say );
//
// schedule portalIfc_indications_1_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_deq,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_say,
// 					     ifc_say2,
// 					     ifc_setLeds );
// schedule portalIfc_indications_1_first  SB ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_2_first,
// 					   portalIfc_indications_2_deq,
// 					   portalIfc_indications_2_notEmpty,
// 					   ifc_say,
// 					   ifc_say2,
// 					   ifc_setLeds );
// schedule portalIfc_indications_1_deq  C ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_deq,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_say,
// 						ifc_setLeds );
// schedule portalIfc_indications_1_notEmpty  SB ( portalIfc_indications_1_deq,
// 						ifc_say2 );
//
// schedule portalIfc_indications_2_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_indications_2_first,
// 					     portalIfc_indications_2_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_say,
// 					     ifc_say2,
// 					     ifc_setLeds );
// schedule portalIfc_indications_2_first  SB ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   ifc_say,
// 					   ifc_say2,
// 					   ifc_setLeds );
// schedule portalIfc_indications_2_deq  C ( portalIfc_indications_2_deq );
//
// schedule portalIfc_indications_2_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_indications_2_first,
// 						portalIfc_indications_2_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_say,
// 						ifc_say2 );
// schedule portalIfc_indications_2_notEmpty  SB ( portalIfc_indications_2_deq,
// 						ifc_setLeds );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_indications_1_first,
// 				     portalIfc_indications_1_notEmpty,
// 				     portalIfc_indications_2_first,
// 				     portalIfc_indications_2_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule portalIfc_intr_status  SB ( portalIfc_indications_0_deq,
// 				     portalIfc_indications_1_deq,
// 				     portalIfc_indications_2_deq,
// 				     ifc_say,
// 				     ifc_say2,
// 				     ifc_setLeds );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_notEmpty,
// 				      portalIfc_indications_2_first,
// 				      portalIfc_indications_2_notEmpty,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel );
// schedule portalIfc_intr_channel  SB ( portalIfc_indications_0_deq,
// 				      portalIfc_indications_1_deq,
// 				      portalIfc_indications_2_deq,
// 				      ifc_say,
// 				      ifc_say2,
// 				      ifc_setLeds );
//
// schedule ifc_say  CF ( portalIfc_messageSize_size,
// 		       portalIfc_indications_0_first,
// 		       portalIfc_indications_0_deq,
// 		       portalIfc_indications_1_first,
// 		       portalIfc_indications_1_deq,
// 		       portalIfc_indications_1_notEmpty,
// 		       portalIfc_indications_2_first,
// 		       portalIfc_indications_2_deq,
// 		       portalIfc_indications_2_notEmpty,
// 		       ifc_say2,
// 		       ifc_setLeds );
// schedule ifc_say  C ( ifc_say );
//
// schedule ifc_say2  CF ( portalIfc_messageSize_size,
// 			portalIfc_indications_0_first,
// 			portalIfc_indications_0_deq,
// 			portalIfc_indications_0_notEmpty,
// 			portalIfc_indications_1_first,
// 			portalIfc_indications_1_deq,
// 			portalIfc_indications_2_first,
// 			portalIfc_indications_2_deq,
// 			portalIfc_indications_2_notEmpty,
// 			ifc_say,
// 			ifc_setLeds );
// schedule ifc_say2  C ( ifc_say2 );
//
// schedule ifc_setLeds  CF ( portalIfc_messageSize_size,
// 			   portalIfc_indications_0_first,
// 			   portalIfc_indications_0_deq,
// 			   portalIfc_indications_0_notEmpty,
// 			   portalIfc_indications_1_first,
// 			   portalIfc_indications_1_deq,
// 			   portalIfc_indications_1_notEmpty,
// 			   portalIfc_indications_2_first,
// 			   portalIfc_indications_2_deq,
// 			   ifc_say,
// 			   ifc_say2 );
// schedule ifc_setLeds  C ( ifc_setLeds );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16
// RDY_portalIfc_messageSize_size  O     1 const
// portalIfc_indications_0_first  O    32 reg
// RDY_portalIfc_indications_0_first  O     1 reg
// RDY_portalIfc_indications_0_deq  O     1 reg
// portalIfc_indications_0_notEmpty  O     1 reg
// RDY_portalIfc_indications_0_notEmpty  O     1 const
// portalIfc_indications_1_first  O    32 reg
// RDY_portalIfc_indications_1_first  O     1 reg
// RDY_portalIfc_indications_1_deq  O     1 reg
// portalIfc_indications_1_notEmpty  O     1 reg
// RDY_portalIfc_indications_1_notEmpty  O     1 const
// portalIfc_indications_2_first  O    32 reg
// RDY_portalIfc_indications_2_first  O     1 reg
// RDY_portalIfc_indications_2_deq  O     1 reg
// portalIfc_indications_2_notEmpty  O     1 reg
// RDY_portalIfc_indications_2_notEmpty  O     1 const
// portalIfc_intr_status          O     1
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32
// RDY_portalIfc_intr_channel     O     1 const
// RDY_ifc_say                    O     1
// RDY_ifc_say2                   O     1
// RDY_ifc_setLeds                O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16
// ifc_say_v                      I    32 reg
// ifc_say2_a                     I    16 reg
// ifc_say2_b                     I    16 reg
// ifc_setLeds_v                  I     8 reg
// EN_portalIfc_indications_0_deq  I     1
// EN_portalIfc_indications_1_deq  I     1
// EN_portalIfc_indications_2_deq  I     1
// EN_ifc_say                     I     1
// EN_ifc_say2                    I     1
// EN_ifc_setLeds                 I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkEchoRequestOutput(CLK,
			   RST_N,

			   portalIfc_messageSize_size_methodNumber,
			   portalIfc_messageSize_size,
			   RDY_portalIfc_messageSize_size,

			   portalIfc_indications_0_first,
			   RDY_portalIfc_indications_0_first,

			   EN_portalIfc_indications_0_deq,
			   RDY_portalIfc_indications_0_deq,

			   portalIfc_indications_0_notEmpty,
			   RDY_portalIfc_indications_0_notEmpty,

			   portalIfc_indications_1_first,
			   RDY_portalIfc_indications_1_first,

			   EN_portalIfc_indications_1_deq,
			   RDY_portalIfc_indications_1_deq,

			   portalIfc_indications_1_notEmpty,
			   RDY_portalIfc_indications_1_notEmpty,

			   portalIfc_indications_2_first,
			   RDY_portalIfc_indications_2_first,

			   EN_portalIfc_indications_2_deq,
			   RDY_portalIfc_indications_2_deq,

			   portalIfc_indications_2_notEmpty,
			   RDY_portalIfc_indications_2_notEmpty,

			   portalIfc_intr_status,
			   RDY_portalIfc_intr_status,

			   portalIfc_intr_channel,
			   RDY_portalIfc_intr_channel,

			   ifc_say_v,
			   EN_ifc_say,
			   RDY_ifc_say,

			   ifc_say2_a,
			   ifc_say2_b,
			   EN_ifc_say2,
			   RDY_ifc_say2,

			   ifc_setLeds_v,
			   EN_ifc_setLeds,
			   RDY_ifc_setLeds);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // value method portalIfc_indications_0_first
  output [31 : 0] portalIfc_indications_0_first;
  output RDY_portalIfc_indications_0_first;

  // action method portalIfc_indications_0_deq
  input  EN_portalIfc_indications_0_deq;
  output RDY_portalIfc_indications_0_deq;

  // value method portalIfc_indications_0_notEmpty
  output portalIfc_indications_0_notEmpty;
  output RDY_portalIfc_indications_0_notEmpty;

  // value method portalIfc_indications_1_first
  output [31 : 0] portalIfc_indications_1_first;
  output RDY_portalIfc_indications_1_first;

  // action method portalIfc_indications_1_deq
  input  EN_portalIfc_indications_1_deq;
  output RDY_portalIfc_indications_1_deq;

  // value method portalIfc_indications_1_notEmpty
  output portalIfc_indications_1_notEmpty;
  output RDY_portalIfc_indications_1_notEmpty;

  // value method portalIfc_indications_2_first
  output [31 : 0] portalIfc_indications_2_first;
  output RDY_portalIfc_indications_2_first;

  // action method portalIfc_indications_2_deq
  input  EN_portalIfc_indications_2_deq;
  output RDY_portalIfc_indications_2_deq;

  // value method portalIfc_indications_2_notEmpty
  output portalIfc_indications_2_notEmpty;
  output RDY_portalIfc_indications_2_notEmpty;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // action method ifc_say
  input  [31 : 0] ifc_say_v;
  input  EN_ifc_say;
  output RDY_ifc_say;

  // action method ifc_say2
  input  [15 : 0] ifc_say2_a;
  input  [15 : 0] ifc_say2_b;
  input  EN_ifc_say2;
  output RDY_ifc_say2;

  // action method ifc_setLeds
  input  [7 : 0] ifc_setLeds_v;
  input  EN_ifc_setLeds;
  output RDY_ifc_setLeds;

  // signals for module outputs
  wire [31 : 0] portalIfc_indications_0_first,
		portalIfc_indications_1_first,
		portalIfc_indications_2_first,
		portalIfc_intr_channel;
  wire [15 : 0] portalIfc_messageSize_size;
  wire RDY_ifc_say,
       RDY_ifc_say2,
       RDY_ifc_setLeds,
       RDY_portalIfc_indications_0_deq,
       RDY_portalIfc_indications_0_first,
       RDY_portalIfc_indications_0_notEmpty,
       RDY_portalIfc_indications_1_deq,
       RDY_portalIfc_indications_1_first,
       RDY_portalIfc_indications_1_notEmpty,
       RDY_portalIfc_indications_2_deq,
       RDY_portalIfc_indications_2_first,
       RDY_portalIfc_indications_2_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       portalIfc_indications_0_notEmpty,
       portalIfc_indications_1_notEmpty,
       portalIfc_indications_2_notEmpty,
       portalIfc_intr_status;

  // ports of submodule indicationPipes
  wire [31 : 0] indicationPipes_methods_say2_enq_v,
		indicationPipes_methods_say_enq_v,
		indicationPipes_portalIfc_indications_0_first,
		indicationPipes_portalIfc_indications_1_first,
		indicationPipes_portalIfc_indications_2_first,
		indicationPipes_portalIfc_intr_channel;
  wire [15 : 0] indicationPipes_portalIfc_messageSize_size,
		indicationPipes_portalIfc_messageSize_size_methodNumber;
  wire [7 : 0] indicationPipes_methods_setLeds_enq_v;
  wire indicationPipes_EN_methods_say2_enq,
       indicationPipes_EN_methods_say_enq,
       indicationPipes_EN_methods_setLeds_enq,
       indicationPipes_EN_portalIfc_indications_0_deq,
       indicationPipes_EN_portalIfc_indications_1_deq,
       indicationPipes_EN_portalIfc_indications_2_deq,
       indicationPipes_RDY_methods_say2_enq,
       indicationPipes_RDY_methods_say_enq,
       indicationPipes_RDY_methods_setLeds_enq,
       indicationPipes_RDY_portalIfc_indications_0_deq,
       indicationPipes_RDY_portalIfc_indications_0_first,
       indicationPipes_RDY_portalIfc_indications_1_deq,
       indicationPipes_RDY_portalIfc_indications_1_first,
       indicationPipes_RDY_portalIfc_indications_2_deq,
       indicationPipes_RDY_portalIfc_indications_2_first,
       indicationPipes_portalIfc_indications_0_notEmpty,
       indicationPipes_portalIfc_indications_1_notEmpty,
       indicationPipes_portalIfc_indications_2_notEmpty,
       indicationPipes_portalIfc_intr_status;

  // value method portalIfc_messageSize_size
  assign portalIfc_messageSize_size =
	     indicationPipes_portalIfc_messageSize_size ;
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // value method portalIfc_indications_0_first
  assign portalIfc_indications_0_first =
	     indicationPipes_portalIfc_indications_0_first ;
  assign RDY_portalIfc_indications_0_first =
	     indicationPipes_RDY_portalIfc_indications_0_first ;

  // action method portalIfc_indications_0_deq
  assign RDY_portalIfc_indications_0_deq =
	     indicationPipes_RDY_portalIfc_indications_0_deq ;

  // value method portalIfc_indications_0_notEmpty
  assign portalIfc_indications_0_notEmpty =
	     indicationPipes_portalIfc_indications_0_notEmpty ;
  assign RDY_portalIfc_indications_0_notEmpty = 1'd1 ;

  // value method portalIfc_indications_1_first
  assign portalIfc_indications_1_first =
	     indicationPipes_portalIfc_indications_1_first ;
  assign RDY_portalIfc_indications_1_first =
	     indicationPipes_RDY_portalIfc_indications_1_first ;

  // action method portalIfc_indications_1_deq
  assign RDY_portalIfc_indications_1_deq =
	     indicationPipes_RDY_portalIfc_indications_1_deq ;

  // value method portalIfc_indications_1_notEmpty
  assign portalIfc_indications_1_notEmpty =
	     indicationPipes_portalIfc_indications_1_notEmpty ;
  assign RDY_portalIfc_indications_1_notEmpty = 1'd1 ;

  // value method portalIfc_indications_2_first
  assign portalIfc_indications_2_first =
	     indicationPipes_portalIfc_indications_2_first ;
  assign RDY_portalIfc_indications_2_first =
	     indicationPipes_RDY_portalIfc_indications_2_first ;

  // action method portalIfc_indications_2_deq
  assign RDY_portalIfc_indications_2_deq =
	     indicationPipes_RDY_portalIfc_indications_2_deq ;

  // value method portalIfc_indications_2_notEmpty
  assign portalIfc_indications_2_notEmpty =
	     indicationPipes_portalIfc_indications_2_notEmpty ;
  assign RDY_portalIfc_indications_2_notEmpty = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = indicationPipes_portalIfc_intr_status ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = indicationPipes_portalIfc_intr_channel ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // action method ifc_say
  assign RDY_ifc_say = indicationPipes_RDY_methods_say_enq ;

  // action method ifc_say2
  assign RDY_ifc_say2 = indicationPipes_RDY_methods_say2_enq ;

  // action method ifc_setLeds
  assign RDY_ifc_setLeds = indicationPipes_RDY_methods_setLeds_enq ;

  // submodule indicationPipes
  mkEchoRequestOutputPipes indicationPipes(.CLK(CLK),
					   .RST_N(RST_N),
					   .methods_say2_enq_v(indicationPipes_methods_say2_enq_v),
					   .methods_say_enq_v(indicationPipes_methods_say_enq_v),
					   .methods_setLeds_enq_v(indicationPipes_methods_setLeds_enq_v),
					   .portalIfc_messageSize_size_methodNumber(indicationPipes_portalIfc_messageSize_size_methodNumber),
					   .EN_methods_say_enq(indicationPipes_EN_methods_say_enq),
					   .EN_methods_say2_enq(indicationPipes_EN_methods_say2_enq),
					   .EN_methods_setLeds_enq(indicationPipes_EN_methods_setLeds_enq),
					   .EN_portalIfc_indications_0_deq(indicationPipes_EN_portalIfc_indications_0_deq),
					   .EN_portalIfc_indications_1_deq(indicationPipes_EN_portalIfc_indications_1_deq),
					   .EN_portalIfc_indications_2_deq(indicationPipes_EN_portalIfc_indications_2_deq),
					   .RDY_methods_say_enq(indicationPipes_RDY_methods_say_enq),
					   .methods_say_notFull(),
					   .RDY_methods_say_notFull(),
					   .RDY_methods_say2_enq(indicationPipes_RDY_methods_say2_enq),
					   .methods_say2_notFull(),
					   .RDY_methods_say2_notFull(),
					   .RDY_methods_setLeds_enq(indicationPipes_RDY_methods_setLeds_enq),
					   .methods_setLeds_notFull(),
					   .RDY_methods_setLeds_notFull(),
					   .portalIfc_messageSize_size(indicationPipes_portalIfc_messageSize_size),
					   .RDY_portalIfc_messageSize_size(),
					   .portalIfc_indications_0_first(indicationPipes_portalIfc_indications_0_first),
					   .RDY_portalIfc_indications_0_first(indicationPipes_RDY_portalIfc_indications_0_first),
					   .RDY_portalIfc_indications_0_deq(indicationPipes_RDY_portalIfc_indications_0_deq),
					   .portalIfc_indications_0_notEmpty(indicationPipes_portalIfc_indications_0_notEmpty),
					   .RDY_portalIfc_indications_0_notEmpty(),
					   .portalIfc_indications_1_first(indicationPipes_portalIfc_indications_1_first),
					   .RDY_portalIfc_indications_1_first(indicationPipes_RDY_portalIfc_indications_1_first),
					   .RDY_portalIfc_indications_1_deq(indicationPipes_RDY_portalIfc_indications_1_deq),
					   .portalIfc_indications_1_notEmpty(indicationPipes_portalIfc_indications_1_notEmpty),
					   .RDY_portalIfc_indications_1_notEmpty(),
					   .portalIfc_indications_2_first(indicationPipes_portalIfc_indications_2_first),
					   .RDY_portalIfc_indications_2_first(indicationPipes_RDY_portalIfc_indications_2_first),
					   .RDY_portalIfc_indications_2_deq(indicationPipes_RDY_portalIfc_indications_2_deq),
					   .portalIfc_indications_2_notEmpty(indicationPipes_portalIfc_indications_2_notEmpty),
					   .RDY_portalIfc_indications_2_notEmpty(),
					   .portalIfc_intr_status(indicationPipes_portalIfc_intr_status),
					   .RDY_portalIfc_intr_status(),
					   .portalIfc_intr_channel(indicationPipes_portalIfc_intr_channel),
					   .RDY_portalIfc_intr_channel());

  // submodule indicationPipes
  assign indicationPipes_methods_say2_enq_v = { ifc_say2_a, ifc_say2_b } ;
  assign indicationPipes_methods_say_enq_v = ifc_say_v ;
  assign indicationPipes_methods_setLeds_enq_v = ifc_setLeds_v ;
  assign indicationPipes_portalIfc_messageSize_size_methodNumber =
	     portalIfc_messageSize_size_methodNumber ;
  assign indicationPipes_EN_methods_say_enq = EN_ifc_say ;
  assign indicationPipes_EN_methods_say2_enq = EN_ifc_say2 ;
  assign indicationPipes_EN_methods_setLeds_enq = EN_ifc_setLeds ;
  assign indicationPipes_EN_portalIfc_indications_0_deq =
	     EN_portalIfc_indications_0_deq ;
  assign indicationPipes_EN_portalIfc_indications_1_deq =
	     EN_portalIfc_indications_1_deq ;
  assign indicationPipes_EN_portalIfc_indications_2_deq =
	     EN_portalIfc_indications_2_deq ;
endmodule  // mkEchoRequestOutput

